name: indovina-chi

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./config:/config

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_SOCKET_URL=${VITE_SOCKET_URL:-}
    ports:
      - "5173:5173"
    depends_on:
      - server